# Generated by Django 2.2.19 on 2021-04-15 17:23

import aplic.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('dataInicio', models.DateField(verbose_name='Data de Início')),
                ('dataTermino', models.DateField(verbose_name='Data de Término')),
                ('regras', models.TextField(verbose_name='Regras')),
                ('premiacao', models.TextField(verbose_name='Premiação')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('MOBA', 'MOBA'), ('FPS', 'FPS'), ('Battle Royale', 'Battle Royale'), ('Esporte', 'Esporte')], max_length=30, verbose_name='Categoria')),
                ('desenvolvedor', models.CharField(choices=[('RIOT', 'RIOT GAMES'), ('GARENA', 'GARENA'), ('VALVE', 'VALVE'), ('EPIC GAMES', 'EPIC GAMES'), ('EA SPORTS', 'EASPORTS'), ('PUBG CORPORATION', 'PUBG CORPORATION')], max_length=30, verbose_name='Desenvolvedor')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(verbose_name='idade')),
                ('foto', stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('bandeira', stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='idade')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('foto', stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto')),
                ('jogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Jogo')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Time')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Campeonato')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Jogo')),
                ('time', models.ManyToManyField(max_length=50, to='aplic.Time')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='idade')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('foto', stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto')),
                ('jogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Jogo')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Time')),
            ],
            options={
                'verbose_name': 'Competidor',
                'verbose_name_plural': 'Competidores',
            },
        ),
        migrations.AddField(
            model_name='campeonato',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Jogo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Organizador'),
        ),
    ]
