# Generated by Django 2.2.19 on 2021-04-15 19:04

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto'),
        ),
    ]
