# Generated by Django 2.2.19 on 2021-04-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20210416_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Campeonato')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Jogo')),
                ('mvp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Competidor')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Partida')),
                ('vencedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Time')),
            ],
        ),
    ]
