# Generated by Django 2.2.19 on 2021-04-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_resultado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
