# Generated by Django 2.2.19 on 2021-04-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_delete_resultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('placar', models.CharField(max_length=100, verbose_name='Placar')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Campeonato')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Jogo')),
                ('mvp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Competidor')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Partida')),
                ('time', models.ManyToManyField(to='aplic.Time')),
                ('vencedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Time_content_type', to='aplic.Time')),
            ],
        ),
    ]
